version: '2.1'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: "SchedulegenDB"
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "4444:5432"
    volumes:
      - pg_dev_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  pg_dev_data:


#  app:  # ← Ваше Spring Boot приложение
#    depends_on:
#      postgres:
#        condition: service_healthy  # Ждёт пока postgres станет healthy