spring.datasource.url=jdbc:postgresql://localhost:4444/SchedulegenDB
spring.datasource.username=user
spring.datasource.password=oHQjGK83gXLWdhhwwQmE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.url=jdbc:postgresql://localhost:4444/SchedulegenDB
spring.flyway.user=user
spring.flyway.password=oHQjGK83gXLWdhhwwQmE
spring.flyway.schemas=public
spring.flyway.locations=filesystem:sql/migrations
