spring.application.name=ScheduleGen
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://localhost:5432/scheme_name
spring.datasource.username=postgres
spring.datasource.password=postgres