BEGIN;

-- 1. ЗДАНИЯ И АУДИТОРИИ

CREATE TABLE building (
    building_id   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    building_name varchar NOT NULL UNIQUE,
    address       varchar
);

CREATE TABLE audience (
    audience_id     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_name       varchar(10) UNIQUE NOT NULL,
    building_id     integer NOT NULL REFERENCES building (building_id),
    amount_of_seats integer NOT NULL
);

CREATE TABLE roomtype (
    room_type_id   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_type_name varchar NOT NULL UNIQUE
);

CREATE TABLE audience_roomtype (
    room_type_id integer NOT NULL REFERENCES roomtype (room_type_id),
    audience_id  integer NOT NULL REFERENCES audience (audience_id),
    PRIMARY KEY (room_type_id, audience_id)
);


-- 2. ВРЕМЕННАЯ СЕТКА

CREATE TABLE pairtimeborders (
    pair_number integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pair_start  time NOT NULL,
    pair_end    time NOT NULL,
    UNIQUE (pair_start, pair_end)
);

CREATE TABLE timeslot (
    time_slot_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    day_of_week  integer NOT NULL,
    pair_number  integer NOT NULL REFERENCES pairtimeborders (pair_number),
    UNIQUE (day_of_week, pair_number)
);


-- 3. ФАКУЛЬТЕТ, СПЕЦИАЛИЗАЦИЯ, ГРУППЫ

CREATE TABLE faculty (
    faculty_id   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    faculty_name varchar NOT NULL UNIQUE
);

CREATE TABLE specialization (
    spec_id       integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    spec_name     varchar NOT NULL,
    faculty_id    integer NOT NULL REFERENCES faculty (faculty_id),
    years_of_study integer
);

CREATE TABLE subgroup (
    subgroup_id   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subgroup_name varchar(20) NOT NULL
);

CREATE TABLE students_group (
    students_group_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_name        varchar(10) NOT NULL UNIQUE,
    spec_id           integer NOT NULL REFERENCES specialization (spec_id),
    students_count    integer NOT NULL
);

CREATE TABLE students_group_subgroup (
    students_group_id integer NOT NULL REFERENCES students_group (students_group_id),
    subgroup_id       integer NOT NULL REFERENCES subgroup (subgroup_id),
    PRIMARY KEY (students_group_id, subgroup_id)
);


-- 4. ПРЕПОДАВАТЕЛИ

CREATE TABLE professor (
    professor_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name   varchar NOT NULL,
    last_name    varchar NOT NULL,
    email        varchar NOT NULL UNIQUE,
    phone_number varchar NOT NULL UNIQUE
);


-- 5. ДИСЦИПЛИНЫ (объединённая таблица)

CREATE TABLE discipline (
    discipline_id      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    discipline_name    varchar(40) NOT NULL,
    study_semester     integer NOT NULL,
    required_room_type integer REFERENCES roomtype (room_type_id),
    credits            float NOT NULL,
    spec_id            integer NOT NULL REFERENCES specialization (spec_id),
    -- часы
    contact_hours      float NOT NULL,
    independent_hours  float,
    course_hours       float NOT NULL,
    seminar_hours      float NOT NULL,
    lab_hours          float NOT NULL,
    UNIQUE (discipline_name, study_semester, spec_id)
);

CREATE TABLE professor_discipline (
    professor_id  integer NOT NULL REFERENCES professor (professor_id),
    discipline_id integer NOT NULL REFERENCES discipline (discipline_id),
    PRIMARY KEY (professor_id, discipline_id)
);

-- 6. ЗАПУСК АЛГОРИТМА (бывший schedule_generation)
CREATE TABLE ga_run (
    ga_run_id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    students_group_id integer NOT NULL REFERENCES students_group (students_group_id),
    weeks_in_cycle    integer NOT NULL,
    created_at        timestamp NOT NULL DEFAULT now()
);

-- ПОКОЛЕНИЕ внутри запуска
CREATE TABLE ga_generation (
    ga_generation_id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ga_run_id         integer NOT NULL REFERENCES ga_run (ga_run_id),
    generation_number integer NOT NULL,
    UNIQUE (ga_run_id, generation_number)
);

-- ХРОМОСОМА внутри поколения
CREATE TABLE chromosome (
    chromosome_id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ga_generation_id integer NOT NULL REFERENCES ga_generation (ga_generation_id),
    fitness_score    float
);

-- СПИСОК ДИСЦИПЛИН хромосомы (гены — упорядоченный список)
CREATE TABLE chromosome_discipline (
    chromosome_id integer NOT NULL REFERENCES chromosome (chromosome_id),
    position      integer NOT NULL,
    discipline_id integer NOT NULL REFERENCES discipline (discipline_id),
    PRIMARY KEY (chromosome_id, position)
);

-- РАСПИСАНИЕ привязано к хромосоме
CREATE TABLE schedule (
    chromosome_id integer NOT NULL REFERENCES chromosome (chromosome_id),
    week_number   integer NOT NULL,
    time_slot_id  integer NOT NULL REFERENCES timeslot (time_slot_id),
    audience_id   integer NOT NULL REFERENCES audience (audience_id),
    discipline_id integer NOT NULL REFERENCES discipline (discipline_id),
    professor_id  integer NOT NULL REFERENCES professor (professor_id),
    PRIMARY KEY (chromosome_id, week_number, time_slot_id),
    UNIQUE (chromosome_id, week_number, time_slot_id, professor_id),
    UNIQUE (chromosome_id, week_number, time_slot_id, audience_id)
);

-- 7. ОГРАНИЧЕНИЯ И ПОЖЕЛАНИЯ

CREATE TYPE constraint_kind AS ENUM ('hard', 'soft');

CREATE TABLE constraint_type (
    constraint_type_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_name          varchar NOT NULL UNIQUE,
    description        varchar
);

-- базовые типы ограничений
INSERT INTO constraint_type (type_name, description) VALUES
    ('NO_CLASS_AFTER_TIME',   'Не ставить пары позже указанного времени'),
    ('NO_CLASS_BEFORE_TIME',  'Не ставить пары раньше указанного времени'),
    ('NO_CLASS_ON_DATE',      'Не ставить пары в указанные даты/время'),
    ('NO_FIRST_PAIR',         'Не ставить первую пару'),
    ('NO_WINDOWS',            'Не допускать окон в расписании'),
    ('MAX_WINDOWS',           'Ограничение на максимальное количество окон');

-- ОГРАНИЧЕНИЯ привязаны к запуску
CREATE TABLE schedule_constraint (
    constraint_id      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ga_run_id          integer NOT NULL REFERENCES ga_run (ga_run_id),
    constraint_type_id integer NOT NULL REFERENCES constraint_type (constraint_type_id),
    kind               constraint_kind NOT NULL,
    soft_priority      integer,
    professor_id       integer REFERENCES professor (professor_id),
    parameters         jsonb
);

COMMIT;