BEGIN;

CREATE TABLE audience (
    audience_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_name varchar(10) UNIQUE,
    university_building integer NOT NULL,
    amount_of_seats integer NOT NULL
);

CREATE TABLE roomtype (
    room_type_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_type_name varchar NOT NULL
);

CREATE TABLE audience_roomtype (
    room_type_id integer NOT NULL REFERENCES roomtype (room_type_id),
    audience_id integer NOT NULL REFERENCES audience (audience_id),
    PRIMARY KEY (room_type_id, audience_id)
);

CREATE TABLE pairtimeborders (
    pair_number integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pair_start time NOT NULL,
    pair_end time NOT NULL,
    UNIQUE (pair_start, pair_end)
);

CREATE TABLE timeslot (
    time_slot_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    day_of_week integer NOT NULL,
    pair_number integer NOT NULL REFERENCES pairtimeborders (pair_number),
    UNIQUE (day_of_week, pair_number)
);

CREATE TABLE schedule_generation (
    schedule_generation_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at time
);

CREATE TABLE faculty (
    faculty_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    faculty_name varchar NOT NULL UNIQUE
);

CREATE TABLE specialization (
    spec_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    spec_name varchar NOT NULL,
    faculty_id integer NOT NULL REFERENCES faculty (faculty_id),
    years_of_study integer NOT NULL
);

CREATE TABLE professor (
    professor_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar NOT NULL,
    last_name varchar NOT NULL,
    email varchar NOT NULL,
    phone_number varchar NOT NULL
);

CREATE TABLE students_group (
    students_group_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_name varchar(10) NOT NULL UNIQUE,
    professor_inspector integer REFERENCES professor (professor_id),
    spec_id integer NOT NULL REFERENCES specialization (spec_id)
);

CREATE TABLE student (
    student_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    students_group_id integer REFERENCES students_group (students_group_id),
    first_name varchar NOT NULL,
    last_name varchar NOT NULL,
    email varchar
);

CREATE TABLE group_elder_student (
    students_group_id integer NOT NULL REFERENCES students_group (students_group_id),
    student_id integer NOT NULL REFERENCES student (student_id),
    PRIMARY KEY (students_group_id, student_id)
);

CREATE TABLE discipline (
    discipline_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    discipline_name varchar(40) NOT NULL,
    study_semester integer NOT NULL,
    required_room_type integer REFERENCES roomtype (room_type_id),
    credits float,
    spec_id integer NOT NULL REFERENCES specialization (spec_id),
    UNIQUE (discipline_name, study_semester, spec_id)
);

CREATE TABLE professor_discipline (
    professor_id integer NOT NULL REFERENCES professor (professor_id),
    discipline_id integer NOT NULL REFERENCES discipline (discipline_id),
    PRIMARY KEY (professor_id, discipline_id)
);

CREATE TABLE study_hours (
    discipline_id integer PRIMARY KEY REFERENCES discipline (discipline_id),
    contact_study_hours float,
    independent_study_hours float,
    course_hours float,
    seminar_hours float,
    laboratories_hours float
);

CREATE TABLE schedule (
    schedule_generation_id integer NOT NULL REFERENCES schedule_generation (schedule_generation_id),
    students_group_id integer REFERENCES students_group (students_group_id),
    audience_id integer REFERENCES audience (audience_id),
    discipline_id integer REFERENCES discipline (discipline_id),
    professor_id integer REFERENCES professor (professor_id),
    week_pattern integer NOT NULL,
    time_slot_id integer NOT NULL REFERENCES timeslot (time_slot_id),
    PRIMARY KEY (schedule_generation_id, week_pattern, time_slot_id),
    UNIQUE (schedule_generation_id, week_pattern, time_slot_id, discipline_id),
    UNIQUE (schedule_generation_id, week_pattern, time_slot_id, professor_id),
    UNIQUE (schedule_generation_id, week_pattern, time_slot_id, students_group_id)
);

COMMIT;
